package co.gov.mineneriga.jbpm.orfeo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ConsultaDocumentoResponse implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ConsultaDocumentoResponse() {
    }




}