package co.gov.minminas.jbpm.procesodisciplinario;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SolicitudDisciplinario implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public SolicitudDisciplinario() {
    }




}