package co.gov.minenergia.jbpm.data;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RegistroConsultaRadicado implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public RegistroConsultaRadicado() {
    }




}